### ISSUE TITLE
invite me to devseccon2018

### ISSUE THREAD

**Issue by kernelGadaffi** [DevSecOpsSG/devseccon2018#9]
# Request

Add me to DevSecOpsSG Github Organizations

### A bit about yourself

Name : LEE Wang Hao

Email : LEE_Wang_Hao@tech.gov.sg

Organization : Govtech

Others (Projects/Portfolio) : Pls ASk

**Comment by kernelGadaffi** [comment]
Name: Wang Hao Lee
Email: whelee@gmail.com
Organisation: Same as you

**Comment by 3jmaster** [comment]
invited
